name: Mac OS X build

on:
  workflow_dispatch:
  push:

jobs:
  build_macos:
    name: Build binary on Mac OS X Big Sur 11
    runs-on: macos-11
    
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
        with:
          path: nanopb
          fetch-depth: "0"
      
      - name: Install dependencies
        run: |
          pip3 install --user scons protobuf grpcio-tools pyinstaller
          python3 -c 'import google.protobuf; print(google.protobuf.__file__)'
      
      - name: Run clang tests
        run: |
          cd nanopb/tests
          python3 -m SCons CXX=clang++ CC=clang
      
      - name: Build binary package
        run: |
          cd nanopb
          git clean -dxf
          tools/make_mac_package.sh
      
      - name: Test binary package
        run: |
          tar xzf nanopb/dist/*.tar.gz
          cd nanopb-*/tests
          python3 -m SCons
          cd ../examples/simple
          make
          ./simple
      
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          path: nanopb/dist/*.tar.gz
          name: nanopb-binary-macos

