name: Mac OS X build

on:
  workflow_dispatch:
  push:

jobs:
  build_macos:
    name: Build binary on Mac OS X Big Sur 11
    runs-on: macos-11
    
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
        with:
          path: nanopb
          fetch-depth: "0"
      
      - name: Run clang tests
        run: |
          cd nanopb/tests
          scons CXX=clang++ CC=clang
      
      - name: Build binary package
        run: |
          cd nanopb
          git clean -dxf
          tools/make_mac_package.sh
      
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          path: nanopb/dist/*.tar.gz
          name: nanopb-binary-macos

  test_binary_macos:
    name: Test binary package
    runs-on: macos-11
    needs: build_macos
    
    steps:
        - name: Download binary
          uses: actions/download-artifact@v2
          with:
            name: nanopb-binary-macos
        
        - name: Run test cases
          run: |
            tar xzf nanopb*.tar.gz
            cd nanopb*/tests
            scons
        
        - name: Build example
          run: |
            cd nanopb/examples/simple
            make
            ./simple

